version: '3'
services:
  auth_service:
    image: kurdi/auth-service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.2:5432/auth_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8090
    ports:
      - 8090:8090
    networks:
      startupdocker_basic_env:
        ipv4_address: 10.5.0.10
      
  inventory_service:
    image: kurdi/inventory-service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.2:5432/inventory_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8091
    ports:
      - 8091:8091
    networks:
      startupdocker_basic_env:
        ipv4_address: 10.5.0.11
        

  cart_service:
    image: kurdi/cart-service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.2:5432/cart_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8092
    ports:
      - 8092:8092
    networks:
      startupdocker_basic_env:
        ipv4_address: 10.5.0.12

 
  order_service:
    image: kurdi/order-service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.2:5432/order_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8093
    ports:
      - 8093:8093
    networks:
      startupdocker_basic_env:
        ipv4_address: 10.5.0.13

        
networks:
  startupdocker_basic_env:
    external: true