// <auto-generated />
using System;
using Kurdi.ECommerce.Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kurdi.ECommerce.Inventory.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221224104128_SalesOrders")]
    partial class SalesOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.CategoryAggregate.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Activation")
                        .HasColumnType("boolean")
                        .HasColumnName("activation");

                    b.Property<bool>("IsParent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_parent");

                    b.Property<string>("ParentName")
                        .HasColumnType("text")
                        .HasColumnName("parent");

                    b.HasKey("Name");

                    b.HasIndex("ParentName");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.CategoryAggregate.CategoryDetails", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("text")
                        .HasColumnName("translated_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("LanguageCode", "TranslatedName");

                    b.HasIndex("Name");

                    b.ToTable("categories_details");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.Language", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<bool>("Activation")
                        .HasColumnType("boolean")
                        .HasColumnName("activation");

                    b.Property<string>("LanguageName")
                        .HasColumnType("text")
                        .HasColumnName("language_name");

                    b.HasKey("LanguageCode");

                    b.ToTable("languages");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<bool>("Activation")
                        .HasColumnType("boolean")
                        .HasColumnName("activation");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("SupplierIdentity")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_identity");

                    b.HasKey("Sku");

                    b.HasIndex("CategoryName");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.ProductDetails", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("LanguageCode", "Sku");

                    b.HasIndex("Sku");

                    b.ToTable("product_details");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.SalesOrderAggregate.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Discount")
                        .HasColumnType("double precision")
                        .HasColumnName("discount");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<double>("totalPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("total_price");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("sales_order");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.SalesOrderAggregate.SalesOrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CostPricePerItem")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_price_per_item");

                    b.Property<double>("DiscountPerItem")
                        .HasColumnType("double precision")
                        .HasColumnName("discount_per_item");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SKU")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("sales_order_id");

                    b.Property<double>("SellingPricePerItem")
                        .HasColumnType("double precision")
                        .HasColumnName("selling_price_per_item");

                    b.Property<double>("SellingPricePerItemBeforeDiscount")
                        .HasColumnType("double precision")
                        .HasColumnName("selling_price_per_item_before_discount");

                    b.HasKey("Id");

                    b.HasIndex("SKU");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("sales_order_product");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.SalesOrderAggregate.SalesOrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("sales_order_status");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.CategoryAggregate.Category", b =>
                {
                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.CategoryAggregate.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentName");

                    b.OwnsOne("Kurdi.ECommerce.Inventory.Core.Entities.TimeStamps", "TimeStamps", b1 =>
                        {
                            b1.Property<string>("CategoryName")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("CategoryName");

                            b1.ToTable("categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryName");
                        });

                    b.Navigation("Parent");

                    b.Navigation("TimeStamps");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.CategoryAggregate.CategoryDetails", b =>
                {
                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.CategoryAggregate.Category", "Category")
                        .WithMany("CategotyDetails")
                        .HasForeignKey("Name");

                    b.OwnsOne("Kurdi.ECommerce.Inventory.Core.Entities.TimeStamps", "TimeStamps", b1 =>
                        {
                            b1.Property<string>("CategoryDetailsLanguageCode")
                                .HasColumnType("text");

                            b1.Property<string>("CategoryDetailsTranslatedName")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("CategoryDetailsLanguageCode", "CategoryDetailsTranslatedName");

                            b1.ToTable("categories_details");

                            b1.WithOwner()
                                .HasForeignKey("CategoryDetailsLanguageCode", "CategoryDetailsTranslatedName");
                        });

                    b.Navigation("Category");

                    b.Navigation("Language");

                    b.Navigation("TimeStamps");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.Language", b =>
                {
                    b.OwnsOne("Kurdi.ECommerce.Inventory.Core.Entities.TimeStamps", "TimeStamps", b1 =>
                        {
                            b1.Property<string>("LanguageCode")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("LanguageCode");

                            b1.ToTable("languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageCode");
                        });

                    b.Navigation("TimeStamps");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.Product", b =>
                {
                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.CategoryAggregate.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryName");

                    b.OwnsOne("Kurdi.ECommerce.Inventory.Core.Entities.TimeStamps", "TimeStamps", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("ProductSku");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku");
                        });

                    b.OwnsOne("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.ProductPrices", "ProductPrices", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text");

                            b1.Property<double>("CostPrice")
                                .HasColumnType("double precision")
                                .HasColumnName("cost_price");

                            b1.Property<double>("Discount")
                                .HasColumnType("double precision")
                                .HasColumnName("discount");

                            b1.Property<bool>("IsDiscounted")
                                .HasColumnType("boolean")
                                .HasColumnName("is_discounted");

                            b1.Property<double>("SellingPrice")
                                .HasColumnType("double precision")
                                .HasColumnName("selling_price");

                            b1.HasKey("ProductSku");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku");
                        });

                    b.OwnsOne("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.ProductQuantity", "ProductQuantity", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text");

                            b1.Property<int>("AvailableStock")
                                .HasColumnType("integer")
                                .HasColumnName("available_stock");

                            b1.Property<int>("ReservedStock")
                                .HasColumnType("integer")
                                .HasColumnName("reserved_stock");

                            b1.Property<int>("TotalStock")
                                .HasColumnType("integer")
                                .HasColumnName("total_stock");

                            b1.HasKey("ProductSku");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku");
                        });

                    b.Navigation("Category");

                    b.Navigation("ProductPrices");

                    b.Navigation("ProductQuantity");

                    b.Navigation("TimeStamps");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.ProductDetails", b =>
                {
                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("Sku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Kurdi.ECommerce.Inventory.Core.Entities.TimeStamps", "TimeStamps", b1 =>
                        {
                            b1.Property<string>("ProductDetailsLanguageCode")
                                .HasColumnType("text");

                            b1.Property<string>("ProductDetailsSku")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("ProductDetailsLanguageCode", "ProductDetailsSku");

                            b1.ToTable("product_details");

                            b1.WithOwner()
                                .HasForeignKey("ProductDetailsLanguageCode", "ProductDetailsSku");
                        });

                    b.Navigation("Language");

                    b.Navigation("Product");

                    b.Navigation("TimeStamps");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.SalesOrderAggregate.SalesOrder", b =>
                {
                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.SalesOrderAggregate.SalesOrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.SalesOrderAggregate.SalesOrderProduct", b =>
                {
                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.Product", "Product")
                        .WithMany()
                        .HasForeignKey("SKU");

                    b.HasOne("Kurdi.ECommerce.Inventory.Core.Entities.SalesOrderAggregate.SalesOrder", "SalesOrder")
                        .WithMany()
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.CategoryAggregate.Category", b =>
                {
                    b.Navigation("CategotyDetails");
                });

            modelBuilder.Entity("Kurdi.ECommerce.Inventory.Core.Entities.ProductAggregate.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
