definitions:
  entities.Language:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      language_code:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  products.Product:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      product_details:
        items:
          $ref: '#/definitions/products.ProductDetails'
        type: array
      quantity:
        $ref: '#/definitions/products.ProductQuantity'
      updatedAt:
        type: string
    type: object
  products.ProductDetails:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      language:
        $ref: '#/definitions/entities.Language'
      language_code:
        type: string
      name:
        type: string
      product_id:
        type: integer
      updatedAt:
        type: string
    type: object
  products.ProductQuantity:
    properties:
      available_stock:
        type: integer
      reserved_stock:
        type: integer
      total_stock:
        type: integer
    type: object
info:
  contact:
    email: your@mail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API
  version: "1.0"
paths:
  /v1/products:
    get:
      consumes:
      - application/json
      description: Get all exists books.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/products.Product'
            type: array
      summary: get all exists books
      tags:
      - Books
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
