definitions:
  entities.Language:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      language_code:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  products.Product:
    properties:
      available_stock:
        type: integer
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      product_details:
        items:
          $ref: '#/definitions/products.ProductDetails'
        type: array
      reserved_stock:
        type: integer
      total_stock:
        type: integer
      updatedAt:
        type: string
    type: object
  products.ProductDetails:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      language:
        $ref: '#/definitions/entities.Language'
      language_code:
        type: string
      name:
        type: string
      product_id:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact:
    email: your@mail.com
    name: API Support
  description: This is an inventory API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Inventory API
  version: "1.0"
paths:
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Get all products.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/products.Product'
            type: array
      summary: get all products
      tags:
      - Products
  /api/v1/products/{id}:
    get:
      consumes:
      - application/json
      description: Get book by given ID.
      parameters:
      - description: Product Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/products.Product'
      summary: get book by given ID
      tags:
      - Book
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
